# Generated by Django 5.1.2 on 2024-11-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageUpload", "0002_imagepost_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagepost",
            name="author",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="imagepost",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
