# Generated by Django 5.1.2 on 2024-11-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageUpload", "0003_alter_imagepost_author_alter_imagepost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagepost",
            name="author",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
