# Generated by Django 5.1.2 on 2024-11-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageUpload", "0004_alter_imagepost_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagepost",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterField(
            model_name="imagepost",
            name="image",
            field=models.CharField(max_length=500),
        ),
    ]
