# Generated by Django 5.1.2 on 2024-11-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageUpload", "0005_alter_imagepost_options_alter_imagepost_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagepost",
            name="image",
        ),
        migrations.AddField(
            model_name="imagepost",
            name="cloudflare_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="imagepost",
            name="image_file",
            field=models.ImageField(null=True, upload_to="temp/"),
        ),
    ]
