# Generated by Django 5.1.2 on 2024-11-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageUpload", "0007_imagepost_url_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagepost",
            name="cloudflare_path",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
