# Generated by Django 5.1.2 on 2024-11-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("key_management", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="value",
            new_name="keyId",
        ),
    ]
