# Generated by Django 5.1.2 on 2024-11-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("key_management", "0002_rename_value_task_keyid"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("is_encrypted", models.BooleanField(default=True)),
                ("message", models.CharField(max_length=255)),
                ("public_key", models.CharField(max_length=500)),
                ("private_key", models.CharField(max_length=500)),
            ],
        ),
    ]
