# Generated by Django 5.1.2 on 2024-11-12 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageUpload", "0009_imagepost_is_encrypted"),
        ("key_management", "0003_encryptedimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedimage",
            name="image_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="imageUpload.imagepost",
            ),
        ),
    ]
